# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
# SPDX-License-Identifier: MIT

[package]
name = "grpc-digital-twin-adapter"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
async-trait = { workspace = true }
core-protobuf-data-access  = { workspace = true }
freyja-build-common = { workspace = true }
freyja-common = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
freyja-build-common = { workspace = true }

[dev-dependencies]
freyja-test-common = { workspace = true }
tokio-stream = { workspace = true, features = ["net"] }
tower = { workspace = true }